version: '3.9'

services:
  bdd:
    image: mariadb:latest
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: TOOR
      MARIADB_DATABASE: trucmuche
      MARIADB_USER: machin
      MARIADB_PASSWORD: chouette

  api:
    image: arocode/marcelus:main
    restart: always
    ports:
      - 23000:23000
    environment:
      DB_HOST: bdd
      DB_NAME: trucmuche
      DB_USER: machin
      DB_PASS: chouette

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080