version: '3.1'

services:
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: toulouse
      MARIADB_USER: toulouse
      MARIADB_PASSWORD: toulouse